[LIBDOMAIN][FEAT] Reading the schema of objects from the directory service (OpenLDAP)
libdomain/libdomain pull request #70
Opened 2024-08-23 13:29 UTC by Ravenwolve

2024-08-23 17:25 UTC, august-alt requested changes

2024-08-23 17:25 UTC, august-alt commented on tests/docker-compose.openldap.local.yml
Remove file from PR.

2024-08-23 17:25 UTC, august-alt commented on tests/certs/dc0.domain.alt.pem
Remove file from PR.

2024-08-23 17:25 UTC, august-alt commented on tests/certs/dc0.domain.alt.key
Remove file from PR.

2024-08-23 17:25 UTC, august-alt commented on tests/certs/ca.srl
Remove file from PR.

2024-08-23 17:25 UTC, august-alt commented on tests/certs/ca.pem
Remove file from PR.

2024-08-23 17:25 UTC, august-alt commented on tests/certs/ca.key
Remove file from PR.

2024-08-26 06:48 UTC, august-alt requested changes

2024-08-26 06:48 UTC, august-alt commented on docs/source/INTENDED_USAGE.RU.md
Why do we have this file here? This PR clearly addresses LDAP schema and not documentation.

2024-08-26 06:48 UTC, august-alt commented on docs/source/INTENDED_USAGE.md
Why do we have this file here? This PR clearly addresses LDAP schema and not documentation.

2024-08-27 05:11 UTC, august-alt requested changes

2024-08-27 06:24 UTC, Ravenwolve commented on src/openldap_schema.c
> +                callback(current_value, user_data);
> You need to process the return value of a callback function.

Do you want to return failure if not success?

2024-08-27 06:27 UTC, Ravenwolve commented on tests/auto/openldap_schema/openldap_schema.c
> +        schema_load_openldap(connection, schema);
> We have not checked return value of a schema_load_openldap function.

Do you want fail test if not success? And should not we check the schema pointer value?

2024-08-27 11:20 UTC, august-alt requested changes

2024-08-27 11:20 UTC, august-alt commented on src/connection_state_machine.c
> +
`LDAP_CONNECTION_STATE_LOAD_SCHEMA` should be placed before `LDAP_CONNECTION_STATE_RUN`.

2024-08-27 11:20 UTC, august-alt commented on src/connection_state_machine.c
Add `LDAP_CONNECTION_STATE_LOAD_SCHEMA` to `const csm_state_value_t state_strings`.

2024-08-27 11:20 UTC, august-alt commented on src/schema.h
> +ldap_schema_load(struct ldap_connection_ctx_t* connection, struct ldap_schema_t* schema);
Remove `schema` parameter we will receive schema from connection.

2024-08-27 11:20 UTC, august-alt commented on src/schema.c
> +        return RETURN_CODE_SUCCESS;
Replace `RETURN_CODE_SUCCESS` with `RETURN_CODE_FAILURE` for this PR.

2024-08-27 11:20 UTC, august-alt commented on src/schema.c
> +        return RETURN_CODE_SUCCESS;
Replace `RETURN_CODE_SUCCESS` with `RETURN_CODE_FAILURE` for this PR.

2024-08-27 12:36 UTC, august-alt requested changes

2024-08-27 12:36 UTC, august-alt commented on src/connection_state_machine.c
> +        rc = ldap_schema_load(ctx->ctx, ctx->ctx->schema);
New signature of `ldap_schema_load` does not require a `schema` parameter. We need to remove it.

2024-08-27 12:43 UTC, august-alt requested changes

2024-08-27 12:43 UTC, august-alt commented on src/connection_state_machine.c
> +        csm_set_state(ctx, LDAP_CONNECTION_STATE_RUN);
Replace
```c
csm_set_state(ctx, LDAP_CONNECTION_STATE_RUN);
```
with
```c            
csm_set_state(ctx, rc == RETURN_CODE_SUCCESS
              ? LDAP_CONNECTION_STATE_RUN
              : LDAP_CONNECTION_STATE_ERROR);
```

2024-08-27 12:55 UTC, august-alt approved these changes

2024-08-29 12:37 UTC, august-alt approved these changes

2024-08-29 13:01 UTC, august-alt approved these changes

2024-08-30 08:05 UTC, august-alt approved these changes

2024-08-30 11:39 UTC, august-alt approved these changes

2024-08-30 11:54 UTC, merged